#!/usr/bin/env node
// Builds everything that gets installed from the readable sources:
//   n8n/clawd-workflow.json, n8n/clawd-workflow-view.json  <- n8n/clawd-engine.js
//   dist/clawd.ax, dist/clawdcore.ax                        <- awtrix/*.ax, minus comments
//
//   node scripts/build.js          write the files
//   node scripts/build.js --check  fail if any of them is out of date
//
// The engine lives in one plain JS file; this script pastes it into the Code
// nodes so the workflow JSON never drifts from the tested source. The Berry
// scripts are installed without comments and indentation, because AWTRIX needs
// free memory of about the source size to compile a script.
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENGINE = fs.readFileSync(path.join(ROOT, 'n8n', 'clawd-engine.js'), 'utf8');
const MIRROR = fs.readFileSync(path.join(ROOT, 'n8n', 'clawd-mirror.js'), 'utf8');
const E = require(path.join(ROOT, 'n8n', 'clawd-engine.js'));

// ---- Code node bodies ---------------------------------------------------------
const ENGINE_WRAPPER = `

// ---- n8n wrapper (generated by scripts/build.js) ----------------
const staticData = $getWorkflowStaticData('global');
// No TZ in Settings: use n8n's own time zone (Settings > Timezone, or GENERIC_TIMEZONE).
const zone = (typeof $now !== 'undefined' && $now && $now.zoneName) || '';
const results = [];
for (const item of $input.all()) {
  const { cfg, ...input } = item.json;
  const c = Object.assign({}, cfg);
  if (!c.TZ && zone) c.TZ = zone;
  const r = ClawdEngine.runN8n(input, staticData, c, Date.now());
  if (r.ignore) continue;
  results.push({ json: r });
}
return results;
`;

const MIRROR_WRAPPER = `

// ---- n8n wrapper (generated by scripts/build.js) ----------------
const out = [];
for (const item of $input.all()) {
  if (!item.json.mirror || !item.json.payload) continue;
  out.push({ json: { topic: item.json.mirror, message: ClawdMirror.pngBase64(item.json.payload) } });
}
return out;
`;

const GATE_WRAPPER = `

// ---- n8n wrapper (generated by scripts/build.js) ----------------
const staticData = $getWorkflowStaticData('global');
const out = [];
for (const item of $input.all()) {
  const { cfg, ...input } = item.json;
  const g = ClawdMirror.mirrorGate(input, staticData, cfg);
  if (g) out.push({ json: g });
}
return out.slice(0, 1);
`;

const SCREEN_WRAPPER = `

// ---- n8n wrapper (generated by scripts/build.js) ----------------
// A failed or timed-out read arrives as an error item and is skipped.
const out = [];
for (const item of $input.all()) {
  const message = ClawdMirror.screenPngBase64(item.json);
  if (message) out.push({ json: { message } });
}
return out;
`;

const TICK_EVENT = `return [{ json: { event: 'tick' } }];`;

const ACTIVE_EVENT = `// <prefix>/state/apps/active carries the name of the app on screen; the
// settings topic (retained JSON from the view workflow) says whether MIRROR is on.
const out = [];
for (const item of $input.all()) {
  const topic = String(item.json.topic || '');
  const at = topic.lastIndexOf('/state/apps/active');
  if (at < 0) {
    let o = null;
    try { o = JSON.parse(String(item.json.message ?? '')); } catch (e) { /* not settings */ }
    if (o && typeof o.MIRROR === 'boolean') out.push({ json: { event: 'config', mirror: o.MIRROR, source: o.MIRROR_SOURCE } });
    continue;
  }
  out.push({ json: { event: 'active', app: String(item.json.message ?? '').trim().replace(/^"|"$/g, ''), prefix: topic.slice(0, at) } });
}
return out;`;

const MQTT_EVENT = `// AWTRIX NG publishes "1" on press and "0" on release (retained), and the
// name of the app on screen as a plain string. Only presses and app changes
// matter; the engine checks the prefix against the Settings node. Anything
// else this trigger receives is Home Assistant's topic (HA_TOPIC) or the
// settings topic (CONFIG_SET_TOPIC); the engine tells them apart by topic.
const out = [];
for (const item of $input.all()) {
  const topic = String(item.json.topic || '');
  const msg = String(item.json.message ?? '').trim();
  const at = topic.lastIndexOf('/state/');
  if (at < 0) { if (msg) out.push({ json: { event: 'cmd', payload: msg, topic } }); continue; }
  const prefix = topic.slice(0, at);
  const rest = topic.slice(at + 7).split('/');
  if (rest[0] === 'buttons' && rest.length === 2) {
    if (['1', 'true', 'on'].includes(msg.toLowerCase())) out.push({ json: { event: 'button', btn: rest[1], prefix } });
  } else if (rest[0] === 'apps' && rest[1] === 'active') {
    out.push({ json: { event: 'active', app: msg.replace(/^"|"$/g, ''), prefix } });
  }
}
return out;`;

const HA_EVENT = `// Home Assistant (or anything else) posts {"action":"feed"} to this webhook,
// or {"config":{"SOUND":true}} to change settings.
const out = [];
for (const item of $input.all()) {
  const body = item.json.body || item.json;
  const name = String(body.action || '').trim().toLowerCase();
  if (name) out.push({ json: { event: 'action', name } });
  if (body.config && typeof body.config === 'object') out.push({ json: { event: 'config', payload: body.config } });
}
return out;`;

const CMD_EVENT = `// The on-device view script publishes {"a":"feed"} etc. on CMD_TOPIC, Home
// Assistant on HA_TOPIC, settings changes arrive on CONFIG_SET_TOPIC; the
// engine tells them apart by topic.
return $input.all().map((item) => ({ json: { event: 'cmd', payload: String(item.json.message ?? ''), topic: String(item.json.topic || '') } }));`;

const SPLIT_FRAMES = `// One item per extra frame; the next node sends them 250 ms apart.
const out = [];
for (const item of $input.all()) {
  for (const payload of item.json.frames || []) out.push({ json: { base: item.json.base, app: item.json.app, payload } });
}
return out;`;

// ---- Berry minifier ------------------------------------------------------------------
// Keeps the header tags (# @name, # @config ...), drops every other comment,
// indentation and blank line. Strings are respected, escapes included.
function minifyBerry(src) {
  const out = [];
  let header = true;
  for (const raw of src.split('\n')) {
    const t = raw.trim();
    if (header && (t === '' || t.startsWith('#'))) {
      if (t.startsWith('# @')) out.push(t.replace(/\s+/g, ' '));
      continue;
    }
    header = false;
    let cut = t.length;
    for (let i = 0, q = null; i < t.length; i++) {
      const c = t[i];
      if (q) { if (c === '\\') i++; else if (c === q) q = null; }
      else if (c === '"' || c === "'") q = c;
      else if (c === '#') { cut = i; break; }
    }
    const line = t.slice(0, cut).trimEnd();
    if (line) out.push(line);
  }
  return out.join('\n') + '\n';
}

// ---- node helpers ---------------------------------------------------------------
let seq = 0;
const id = (tag) => `clawd-${tag}-${String(++seq).padStart(2, '0')}`;

function code(name, js, pos, notes) {
  const n = { id: id('code'), name, type: 'n8n-nodes-base.code', typeVersion: 2, position: pos, parameters: { jsCode: js } };
  if (notes) n.notes = notes;
  return n;
}

function ifNode(name, expr, pos) {
  return {
    id: id('if'), name, type: 'n8n-nodes-base.if', typeVersion: 2.2, position: pos,
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose', version: 2 },
        conditions: [{ id: id('cond'), leftValue: `={{ ${expr} }}`, rightValue: '', operator: { type: 'boolean', operation: 'true', singleValue: true } }],
        combinator: 'and'
      },
      options: {}
    }
  };
}

// HTTP calls to AWTRIX never fail the execution: n8n only saves the pet's
// state when an execution succeeds, and a sleeping clock must not cost you a
// feeding.
function http(name, method, urlExpr, bodyExpr, pos, extraOptions) {
  return {
    id: id('http'), name, type: 'n8n-nodes-base.httpRequest', typeVersion: 4.2, position: pos,
    onError: 'continueRegularOutput',
    parameters: {
      method, url: urlExpr, sendBody: true, specifyBody: 'json', jsonBody: bodyExpr,
      options: Object.assign({ timeout: 2000 }, extraOptions || {})
    }
  };
}

function settings(mode, pos) {
  const d = E.DEFAULTS;
  const rows = [
    ['MODE', mode, 'string'],
    ['AWTRIX_HOST', d.AWTRIX_HOST, 'string'],
    ['MQTT_PREFIX', d.MQTT_PREFIX, 'string'],
    ['APP_NAME', d.APP_NAME, 'string'],
    ['PET_NAME', d.PET_NAME, 'string'],
    ['TZ', d.TZ, 'string'],
    ['DIFFICULTY', d.DIFFICULTY, 'string'],
    // Empty = the difficulty's value; fill one in to override just that value.
    ...E.PRESET_KEYS.map((k) => [k, '', 'string']),
    ['SLEEP_FROM', d.SLEEP_FROM, 'number'],
    ['SLEEP_TO', d.SLEEP_TO, 'number'],
    ['NIGHT_FROM', d.NIGHT_FROM, 'number'],
    ['NIGHT_TO', d.NIGHT_TO, 'number'],
    ['SOUND', d.SOUND, 'boolean'],
    ['NOTIFY', d.NOTIFY, 'boolean'],
    ['SWITCH_ON_EVENTS', d.SWITCH_ON_EVENTS, 'boolean']
  ];
  if (mode === 'push') rows.push(['BURST', d.BURST, 'boolean'], ['OFFSCREEN_REFRESH_SEC', d.OFFSCREEN_REFRESH_SEC, 'number'], ['STALE_AFTER_SEC', d.STALE_AFTER_SEC, 'number']);
  rows.push(['MIRROR', d.MIRROR, 'boolean']);
  if (mode === 'view') rows.push(['MIRROR_SOURCE', d.MIRROR_SOURCE, 'string'], ['MIRROR_EVERY_SEC', d.MIRROR_EVERY_SEC, 'number'], ['CLOCK', d.CLOCK, 'boolean']);
  rows.push(['MIRROR_TOPIC', d.MIRROR_TOPIC, 'string']);
  rows.push(['STATE_TOPIC', d.STATE_TOPIC, 'string']);
  if (mode === 'view') rows.push(['CMD_TOPIC', d.CMD_TOPIC, 'string']);
  rows.push(['HA_TOPIC', d.HA_TOPIC, 'string'], ['CONFIG_TOPIC', d.CONFIG_TOPIC, 'string'], ['CONFIG_SET_TOPIC', d.CONFIG_SET_TOPIC, 'string']);
  return {
    id: id('set'), name: 'Settings', type: 'n8n-nodes-base.set', typeVersion: 3.4, position: pos,
    notes: 'All of Clawd\'s settings live here. DIFFICULTY is I Can Win, Easy, Medium, Hard or Nightmare; the empty values below it follow the difficulty, fill one in to override it. See docs/REFERENCE.md, "Settings".',
    parameters: {
      assignments: { assignments: rows.map(([k, v, type]) => ({ id: id('opt'), name: `cfg.${k}`, value: v, type })) },
      includeOtherFields: true,
      options: {}
    }
  };
}

const MQTT_CRED = { mqtt: { id: 'REPLACE_WITH_YOUR_MQTT_CREDENTIAL_ID', name: 'AWTRIX broker' } };

function link(conns, from, to, output) {
  conns[from] = conns[from] || { main: [] };
  const o = output || 0;
  while (conns[from].main.length <= o) conns[from].main.push([]);
  conns[from].main[o].push({ node: to, type: 'main', index: 0 });
}

const WF_SETTINGS = {
  executionOrder: 'v1',
  saveDataSuccessExecution: 'none',   // 43,200 ticks a day are not worth keeping
  saveManualExecutions: true,
  saveExecutionProgress: false,
  callerPolicy: 'workflowsFromSameOwner'
};

// Everything that talks to AWTRIX runs in a background sub-workflow (defined
// inline, so there is nothing extra to import). The run that owns the pet's
// state then ends within milliseconds; see runN8n() in the engine.
function awtrixSubWorkflow(parts) {
  const nodes = [
    { id: id('trg'), name: 'From Clawd Engine', type: 'n8n-nodes-base.executeWorkflowTrigger', typeVersion: 1.1, position: [0, 300],
      parameters: { inputSource: 'passthrough' } }
  ];
  const c = {};
  let y = 0;
  const add = (ifName, expr, httpNode) => {
    nodes.push(ifNode(ifName, expr, [220, y]));
    httpNode.position = [440, y];
    nodes.push(httpNode);
    link(c, 'From Clawd Engine', ifName);
    link(c, ifName, httpNode.name);
    y += 160;
  };
  if (parts.includes('frame')) add('Has Frame', '$json.push === true', http('Push Frame', 'PUT', '={{ $json.base }}/api/v1/apps/pushed/{{ $json.app }}', '={{ JSON.stringify($json.payload) }}'));
  add('Has SwitchTo', '$json.switchTo === true', http('Switch To Clawd', 'PUT', '={{ $json.base }}/api/v1/apps/active', '={{ JSON.stringify({ name: $json.app, fast: true }) }}'));
  if (parts.includes('sound')) add('Has Sound', '!!$json.sound', http('Play Sound', 'POST', '={{ $json.base }}/api/v1/audio/play', '={{ JSON.stringify({ rtttl: $json.sound }) }}'));
  add('Has Notify', '!!$json.notify', http('Send Notify', 'POST', '={{ $json.base }}/api/v1/notifications', '={{ JSON.stringify($json.notify) }}'));
  if (parts.includes('burst')) {
    nodes.push(ifNode('Has Burst', '($json.frames || []).length > 0', [220, y]));
    nodes.push(code('Split Frames', SPLIT_FRAMES, [440, y]));
    nodes.push(http('Push Burst Frame', 'PUT', '={{ $json.base }}/api/v1/apps/pushed/{{ $json.app }}', '={{ JSON.stringify($json.payload) }}', [660, y],
      { batching: { batch: { batchSize: 1, batchInterval: 250 } } }));
    link(c, 'From Clawd Engine', 'Has Burst');
    link(c, 'Has Burst', 'Split Frames');
    link(c, 'Split Frames', 'Push Burst Frame');
  }
  return { name: 'Clawd: send to AWTRIX', nodes, connections: c, settings: { executionOrder: 'v1', saveDataSuccessExecution: 'none' } };
}

function background(name, sub, pos) {
  return {
    id: id('exec'), name, type: 'n8n-nodes-base.executeWorkflow', typeVersion: 1.2, position: pos,
    notes: 'Runs the HTTP calls to AWTRIX in the background. The sub-workflow is defined inline (Workflow JSON).',
    parameters: { source: 'parameter', workflowJson: JSON.stringify(sub, null, 1), mode: 'once', options: { waitForSubWorkflow: false } }
  };
}

function triggers(tickName, tickSec, mqttNode, mqttEventName, mqttEventCode) {
  return [
    { id: id('trg'), name: tickName, type: 'n8n-nodes-base.scheduleTrigger', typeVersion: 1.2, position: [-600, 0],
      parameters: { rule: { interval: [{ field: 'seconds', secondsInterval: tickSec }] } } },
    code('Tick Event', TICK_EVENT, [-380, 0]),
    mqttNode,
    code(mqttEventName, mqttEventCode, [-380, 200]),
    { id: id('trg'), name: 'HA Action (Webhook)', type: 'n8n-nodes-base.webhook', typeVersion: 2, position: [-600, 400],
      webhookId: 'clawd-action',
      notes: 'POST {"action":"feed"} - feed, play, clean, med, sleep, wake, stats, reset.',
      parameters: { httpMethod: 'POST', path: 'clawd-action', responseMode: 'onReceived', options: {} } },
    code('HA Event', HA_EVENT, [-380, 400])
  ];
}

// The retained state line (view app, Home Assistant). An MQTT publish is quick,
// so it stays in the main run, like the view mode always had it.
function publishConfig(pos) {
  return { id: id('mqtt'), name: 'Publish Settings', type: 'n8n-nodes-base.mqtt', typeVersion: 1, position: pos,
    credentials: MQTT_CRED, onError: 'continueRegularOutput',
    notes: 'The settings in use, retained on CONFIG_TOPIC (Home Assistant shows them; the mirror workflow reads MIRROR).',
    parameters: { topic: '={{ $json.config.topic }}', sendInputData: false, message: '={{ $json.config.message }}', options: { retain: true, qos: 1 } } };
}

function publishState(pos) {
  return { id: id('mqtt'), name: 'Publish State', type: 'n8n-nodes-base.mqtt', typeVersion: 1, position: pos,
    credentials: MQTT_CRED, onError: 'continueRegularOutput',
    parameters: { topic: '={{ $json.publish.topic }}', sendInputData: false, message: '={{ $json.publish.message }}', options: { retain: true, qos: 1 } } };
}

// ---- push mode --------------------------------------------------------------------
function pushWorkflow() {
  seq = 0;
  const mqttNode = { id: id('trg'), name: 'AWTRIX MQTT', type: 'n8n-nodes-base.mqttTrigger', typeVersion: 1, position: [-600, 200],
    credentials: MQTT_CRED,
    notes: 'Buttons and the app on screen ("+" stands for your MQTT prefix; if the prefix contains a "/", replace "+" with it), plus Home Assistant\'s topic and the settings topic, which must match HA_TOPIC and CONFIG_SET_TOPIC in Settings.',
    parameters: { topics: `+/state/buttons/+,+/state/apps/active,${E.DEFAULTS.HA_TOPIC},${E.DEFAULTS.CONFIG_SET_TOPIC}`, options: {} } };
  const nodes = triggers('Tick every 2s', 2, mqttNode, 'MQTT Event', MQTT_EVENT).concat([
    settings('push', [-160, 200]),
    code('Clawd Engine', ENGINE + ENGINE_WRAPPER, [60, 200], 'Generated from n8n/clawd-engine.js - edit that file and run scripts/build.js.'),
    ifNode('Has State', '!!$json.publish', [280, 0]),
    publishState([500, 0]),
    ifNode('Has Settings', '!!$json.config', [280, -200]),
    publishConfig([500, -200]),
    ifNode('Anything To Send', '$json.push || $json.switchTo || !!$json.sound || !!$json.notify', [280, 200]),
    background('Send To AWTRIX', awtrixSubWorkflow(['frame', 'sound', 'burst']), [500, 200]),
    ifNode('Has Mirror', '$json.push === true && !!$json.mirror', [280, 400]),
    code('Mirror Frame', MIRROR + MIRROR_WRAPPER, [500, 400], 'Generated from n8n/clawd-mirror.js. Only runs with MIRROR on.'),
    { id: id('mqtt'), name: 'Publish Mirror', type: 'n8n-nodes-base.mqtt', typeVersion: 1, position: [720, 400],
      credentials: MQTT_CRED, onError: 'continueRegularOutput',
      parameters: { topic: '={{ $json.topic }}', sendInputData: false, message: '={{ $json.message }}', options: { retain: true, qos: 0 } } }
  ]);
  const c = {};
  link(c, 'Tick every 2s', 'Tick Event');
  link(c, 'AWTRIX MQTT', 'MQTT Event');
  link(c, 'HA Action (Webhook)', 'HA Event');
  for (const n of ['Tick Event', 'MQTT Event', 'HA Event']) link(c, n, 'Settings');
  link(c, 'Settings', 'Clawd Engine');
  link(c, 'Clawd Engine', 'Has State');
  link(c, 'Has State', 'Publish State');
  link(c, 'Clawd Engine', 'Has Settings');
  link(c, 'Has Settings', 'Publish Settings');
  link(c, 'Clawd Engine', 'Anything To Send');
  link(c, 'Anything To Send', 'Send To AWTRIX');
  link(c, 'Clawd Engine', 'Has Mirror');
  link(c, 'Has Mirror', 'Mirror Frame');
  link(c, 'Mirror Frame', 'Publish Mirror');
  return { name: 'Clawd (push mode)', nodes, connections: c, active: false, settings: WF_SETTINGS, meta: { clawdEngine: E.ENGINE_VERSION } };
}

// ---- view mode --------------------------------------------------------------------
function viewWorkflow() {
  seq = 0;
  const mqttNode = { id: id('trg'), name: 'Device Commands (MQTT)', type: 'n8n-nodes-base.mqttTrigger', typeVersion: 1, position: [-600, 200],
    credentials: MQTT_CRED,
    notes: 'The Clawd script\'s commands (its "Command topic" setting, CMD_TOPIC in Settings), Home Assistant\'s (HA_TOPIC) and settings changes (CONFIG_SET_TOPIC).',
    parameters: { topics: `${E.DEFAULTS.CMD_TOPIC},${E.DEFAULTS.HA_TOPIC},${E.DEFAULTS.CONFIG_SET_TOPIC}`, options: {} } };
  const nodes = triggers('Tick every 15s', 15, mqttNode, 'Command Event', CMD_EVENT).concat([
    settings('view', [-160, 200]),
    code('Clawd Engine', ENGINE + ENGINE_WRAPPER, [60, 200], 'Generated from n8n/clawd-engine.js - edit that file and run scripts/build.js.'),
    ifNode('Has State', '!!$json.publish', [280, 100]),
    publishState([500, 100]),
    ifNode('Has Settings', '!!$json.config', [280, -100]),
    publishConfig([500, -100]),
    ifNode('Anything To Send', '$json.switchTo || !!$json.notify', [280, 300]),
    background('Send To AWTRIX', awtrixSubWorkflow([]), [500, 300]),
    ifNode('Has Mirror', '!!$json.mirror && !!$json.payload', [280, 500]),
    code('Mirror Frame', MIRROR + MIRROR_WRAPPER, [500, 500], 'Generated from n8n/clawd-mirror.js. Only runs with MIRROR on and MIRROR_SOURCE "render".'),
    { id: id('mqtt'), name: 'Publish Mirror', type: 'n8n-nodes-base.mqtt', typeVersion: 1, position: [720, 500],
      credentials: MQTT_CRED, onError: 'continueRegularOutput',
      parameters: { topic: '={{ $json.topic }}', sendInputData: false, message: '={{ $json.message }}', options: { retain: true, qos: 0 } } }
  ]);
  const c = {};
  link(c, 'Tick every 15s', 'Tick Event');
  link(c, 'Device Commands (MQTT)', 'Command Event');
  link(c, 'HA Action (Webhook)', 'HA Event');
  for (const n of ['Tick Event', 'Command Event', 'HA Event']) link(c, n, 'Settings');
  link(c, 'Settings', 'Clawd Engine');
  link(c, 'Clawd Engine', 'Has State');
  link(c, 'Clawd Engine', 'Has Settings');
  link(c, 'Clawd Engine', 'Anything To Send');
  link(c, 'Has State', 'Publish State');
  link(c, 'Has Settings', 'Publish Settings');
  link(c, 'Anything To Send', 'Send To AWTRIX');
  link(c, 'Clawd Engine', 'Has Mirror');
  link(c, 'Has Mirror', 'Mirror Frame');
  link(c, 'Mirror Frame', 'Publish Mirror');
  return { name: 'Clawd (view mode)', nodes, connections: c, active: false, settings: WF_SETTINGS, meta: { clawdEngine: E.ENGINE_VERSION } };
}

// ---- view mode: screen mirror ---------------------------------------------------------
// While Clawd is on screen, read the clock's framebuffer every 10 s and publish it as a PNG.
function mirrorWorkflow() {
  seq = 0;
  const d = E.DEFAULTS;
  const rows = [['MIRROR', false, 'boolean'], ['AWTRIX_HOST', d.AWTRIX_HOST, 'string'], ['MQTT_PREFIX', d.MQTT_PREFIX, 'string'],
    ['APP_NAME', d.APP_NAME, 'string'], ['MIRROR_TOPIC', d.MIRROR_TOPIC, 'string']];
  const nodes = [
    { id: id('trg'), name: 'Tick every 10s', type: 'n8n-nodes-base.scheduleTrigger', typeVersion: 1.2, position: [-600, 0],
      notes: 'How often the screen is read while Clawd is shown. Keep it at 5 s or more: each read is an HTTP request the clock has to answer.',
      parameters: { rule: { interval: [{ field: 'seconds', secondsInterval: 10 }] } } },
    code('Tick Event', TICK_EVENT, [-380, 0]),
    { id: id('trg'), name: 'App On Screen (MQTT)', type: 'n8n-nodes-base.mqttTrigger', typeVersion: 1, position: [-600, 200],
      credentials: MQTT_CRED,
      notes: '"+" stands for your MQTT prefix; if the prefix contains a "/", replace "+" with it. The second topic is CONFIG_TOPIC of the view workflow: its MIRROR switches this one on and off.',
      parameters: { topics: `+/state/apps/active,${E.DEFAULTS.CONFIG_TOPIC}`, options: {} } },
    code('Active Event', ACTIVE_EVENT, [-380, 200]),
    { id: id('set'), name: 'Settings', type: 'n8n-nodes-base.set', typeVersion: 3.4, position: [-160, 100],
      notes: 'Same values as the view workflow\'s Settings. MIRROR here is only the starting value: the view workflow\'s MIRROR (on CONFIG_TOPIC) takes over as soon as it is published. See docs/REFERENCE.md, "Seeing the pet".',
      parameters: {
        assignments: { assignments: rows.map(([k, v, type]) => ({ id: id('opt'), name: `cfg.${k}`, value: v, type })) },
        includeOtherFields: true, options: {}
      } },
    code('Mirror Gate', MIRROR + GATE_WRAPPER, [60, 100], 'Generated from n8n/clawd-mirror.js. Passes only while MIRROR is on and Clawd is on screen.'),
    { id: id('http'), name: 'Read Screen', type: 'n8n-nodes-base.httpRequest', typeVersion: 4.2, position: [280, 100],
      onError: 'continueRegularOutput',
      parameters: { method: 'GET', url: '={{ $json.url }}', options: { timeout: 2000 } } },
    code('Screen To PNG', MIRROR + SCREEN_WRAPPER, [500, 100], 'Generated from n8n/clawd-mirror.js.'),
    { id: id('mqtt'), name: 'Publish Mirror', type: 'n8n-nodes-base.mqtt', typeVersion: 1, position: [720, 100],
      credentials: MQTT_CRED, onError: 'continueRegularOutput',
      parameters: { topic: '={{ $(\'Mirror Gate\').first().json.topic }}', sendInputData: false, message: '={{ $json.message }}', options: { retain: true, qos: 0 } } }
  ];
  const c = {};
  link(c, 'Tick every 10s', 'Tick Event');
  link(c, 'App On Screen (MQTT)', 'Active Event');
  for (const n of ['Tick Event', 'Active Event']) link(c, n, 'Settings');
  link(c, 'Settings', 'Mirror Gate');
  link(c, 'Mirror Gate', 'Read Screen');
  link(c, 'Read Screen', 'Screen To PNG');
  link(c, 'Screen To PNG', 'Publish Mirror');
  return { name: 'Clawd (view mode mirror)', nodes, connections: c, active: false, settings: WF_SETTINGS, meta: { clawdEngine: E.ENGINE_VERSION } };
}

// ---- Home Assistant: one MQTT discovery message for the whole pet ---------------------------
// Publish homeassistant/clawd-discovery.json, retained, to homeassistant/device/clawd/config
// and Home Assistant creates a "Clawd" device: sensors read the state line, buttons send
// actions, the camera shows MIRROR_TOPIC, and the settings controls read CONFIG_TOPIC and
// write CONFIG_SET_TOPIC. For push and view mode (device mode has no n8n to answer).
function haDiscovery() {
  const d = E.DEFAULTS, cmps = {};
  const field = (i) => `{% set f = value.split(',') %}{{ f[${i}] | int }}`;
  const pct = (i) => `{% set f = value.split(',') %}{{ ((f[${i}] | int) / 100) | round(0) | int }}`;
  const flag = (i, on) => `{% set f = value.split(',') %}{{ 'ON' if f[${i}] == '${on}' else 'OFF' }}`;
  const sensor = (id, name, icon, tpl, extra) => {
    cmps[id] = Object.assign({ p: 'sensor', name, unique_id: `clawd_${id}`, icon, value_template: tpl, expire_after: 180 }, extra || {});
  };
  sensor('stage', 'Stage', 'mdi:egg-easter',
    "{% set f = value.split(',') %}{% set st = f[1] | int %}{% set ev = f[2] | int %}{% set va = f[3] | int %}" +
    "{% set old = (f[22] if f | length > 22 else '0') == '1' %}" +
    "{{ 'Egg' if st == 0 else ('Passed away (old age)' if old else 'Dead') if st == 2 else " +
    "(['Egg', 'Baby', 'Child', 'Teen', 'Adult', 'Elder', 'Legend'][ev] ~ " +
    "((' (well raised)' if va == 0 else ' (neglected)' if va == 2 else '') if ev in [4, 5] else '')) }}");
  for (const [id, name, icon, i] of [['food', 'Food', 'mdi:food-drumstick', 4], ['happiness', 'Happiness', 'mdi:emoticon-happy', 5],
    ['energy', 'Energy', 'mdi:lightning-bolt', 6], ['hygiene', 'Hygiene', 'mdi:shower', 7], ['health', 'Health', 'mdi:heart-pulse', 8]]) {
    sensor(id, name, icon, pct(i), { unit_of_measurement: '%', state_class: 'measurement' });
  }
  // What comes next, worked out by n8n from the real settings (state line fields 23 and 24).
  sensor('next_stage', 'Next stage in', 'mdi:timer-sand',
    "{% set f = value.split(',') %}{{ ((f[23] | int) / 3600) | round(1) if f | length > 24 and (f[23] | int) >= 0 else 'unknown' }}",
    { unit_of_measurement: 'h' });
  sensor('next_stage_name', 'Next stage', 'mdi:arrow-right-bold',
    "{% set f = value.split(',') %}{% set n = (f[24] | int) if f | length > 24 else 0 %}" +
    "{{ {1: 'Baby', 2: 'Child', 3: 'Teen', 4: 'Adult', 5: 'Elder', 6: 'Legend', 9: 'Passes away'}.get(n, 'None') }}");
  sensor('age', 'Age', 'mdi:cake-variant', "{% set f = value.split(',') %}{{ ((f[15] | int) / 3600) | round(1) }}", { unit_of_measurement: 'h', state_class: 'measurement' });
  sensor('poop', 'Poop', 'mdi:emoticon-poop', field(9));
  sensor('care', 'Care score', 'mdi:hand-heart', field(14), { state_class: 'measurement' });
  sensor('generation', 'Generation', 'mdi:family-tree', field(13));
  for (const [id, name, icon, i, on, cls] of [['asleep', 'Asleep', 'mdi:sleep', 11, '1'], ['sick', 'Sick', 'mdi:emoticon-sick', 10, '1', 'problem']]) {
    cmps[id] = Object.assign({ p: 'binary_sensor', name, unique_id: `clawd_${id}`, icon, value_template: flag(i, on), expire_after: 180 }, cls ? { device_class: cls } : {});
  }
  for (const [a, name, icon] of [['feed', 'Feed', 'mdi:food-drumstick'], ['play', 'Play', 'mdi:star'], ['clean', 'Clean', 'mdi:broom'],
    ['med', 'Medicine', 'mdi:pill'], ['sleep', 'Sleep', 'mdi:power-sleep'], ['wake', 'Wake up', 'mdi:weather-sunny'],
    ['stats', 'Show stats', 'mdi:chart-box'], ['reset', 'New egg', 'mdi:egg']]) {
    cmps[`btn_${a}`] = { p: 'button', name, unique_id: `clawd_btn_${a}`, icon, command_topic: d.HA_TOPIC, payload_press: a };
  }
  cmps.screen = { p: 'camera', name: 'Screen', unique_id: 'clawd_screen', icon: 'mdi:led-strip', topic: d.MIRROR_TOPIC, image_encoding: 'b64' };

  const common = (k, name, icon) => ({ name, unique_id: `clawd_set_${k.toLowerCase()}`, icon, entity_category: 'config',
    command_topic: d.CONFIG_SET_TOPIC, state_topic: d.CONFIG_TOPIC });
  for (const [k, kind, name, icon, unit, step] of E.LIVE_SETTINGS) {
    const id = `set_${k.toLowerCase()}`;
    if (kind === 'bool') {
      cmps[id] = Object.assign({ p: 'switch' }, common(k, name, icon), {
        payload_on: JSON.stringify({ [k]: true }), payload_off: JSON.stringify({ [k]: false }),
        value_template: `{{ 'ON' if value_json.${k} else 'OFF' }}`, state_on: 'ON', state_off: 'OFF' });
    } else if (kind === 'select') {
      cmps[id] = Object.assign({ p: 'select' }, common(k, name, icon), { options: Object.keys(E.PRESETS),
        command_template: `{"${k}": {{ value | tojson }} }`, value_template: `{{ value_json.${k} }}` });
    } else if (kind === 'number') {
      const [min, max] = E.NUM_RANGES[k];
      cmps[id] = Object.assign({ p: 'number' }, common(k, name, icon), { mode: 'box', min, max, step },
        unit ? { unit_of_measurement: unit } : {},
        { command_template: `{"${k}": {{ value }} }`, value_template: `{{ value_json.${k} }}` });
    } else {
      cmps[id] = Object.assign({ p: 'text' }, common(k, name, icon), { max: k === 'PET_NAME' ? 12 : 64,
        command_template: `{"${k}": {{ value | tojson }} }`, value_template: `{{ value_json.${k} }}` });
    }
  }
  cmps.set_reset = Object.assign({ p: 'button' }, common('RESET', 'Reset settings', 'mdi:restore'), { payload_press: '{"reset":true}' });
  delete cmps.set_reset.state_topic;
  return {
    dev: { ids: ['clawd'], name: 'Clawd', mdl: 'Virtual pet', mf: 'Clawd off-device' },
    o: { name: 'clawd-hybrid-pet' },
    state_topic: d.STATE_TOPIC,
    cmps
  };
}

// ---- main ---------------------------------------------------------------------------
const json = (wf) => JSON.stringify(wf, null, 2) + '\n';
const berry = (f) => minifyBerry(fs.readFileSync(path.join(ROOT, 'awtrix', f), 'utf8'));
const outputs = {
  'n8n/clawd-workflow.json': json(pushWorkflow()),
  'n8n/clawd-workflow-view.json': json(viewWorkflow()),
  'n8n/clawd-workflow-mirror.json': json(mirrorWorkflow()),
  'homeassistant/clawd-discovery.json': json(haDiscovery()),
  'dist/clawd.ax': berry('clawd-view.ax'),
  'dist/clawdcore.ax': berry('clawdcore.ax')
};
const check = process.argv.includes('--check');
let stale = 0;
fs.mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
for (const [rel, text] of Object.entries(outputs)) {
  const file = path.join(ROOT, rel);
  if (check) {
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (cur !== text) { console.error(`${rel} is out of date - run: node scripts/build.js`); stale++; }
  } else {
    fs.writeFileSync(file, text);
    console.log(`wrote ${rel} (${text.length} bytes)`);
  }
}
if (stale) process.exit(1);
